[package]
name = "btmap_macro"
version = "0.1.0"
authors = ["ArsileLuci <arsile410@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = { version = "0.5" }
proc-macro2 = "1.0.12"
quote = "1.0"
syn =  {version = "1.0.21", features = ["full"]}