[package]
name = "3_9"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
structopt = { version = "0.3" }
config = {version = "0.10.1", features = ["toml"]}
serde = {version = "1.0.110", features = ["derive"]}
humantime-serde = "1.0.0"