[package]
name = "3_11"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
reqwest = "0.10.4"
futures = {version = "0.3.5", features = []}
tokio = {version = "0.2.21", features = ["full","rt-threaded", "macros"]}
structopt = {version = "0.3.14"}
num_cpus ="1.13"